# Generated by Django 3.2.20 on 2023-09-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeals',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='appeal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.appeals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='photo_good',
            field=models.ImageField(default=1, upload_to='photos/goods/%Y/%m/%d/', verbose_name='Фото товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeals',
            name='buyer',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID закупщика'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='client',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID клиента'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='manager',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID менеджера'),
        ),
    ]
