# Generated by Django 3.2.20 on 2023-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230916_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_description',
            field=models.CharField(max_length=500, verbose_name='Описание товара'),
        ),
    ]
