# Generated by Django 3.2.20 on 2023-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230916_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='link_url',
            field=models.CharField(max_length=200, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Название товара'),
        ),
    ]
