# Generated by Django 3.2.20 on 2023-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230916_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price_delivery',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
