# Generated by Django 3.2.20 on 2023-09-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_goods_price_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='appeal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.appeals'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
