# Generated by Django 3.2.20 on 2023-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230918_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo_good',
            field=models.ImageField(blank=True, null=True, upload_to='photos/goods/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_rmb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена товара в Китае в юанях'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество'),
        ),
    ]
