# Generated by Django 3.2.20 on 2023-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230918_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeals',
            name='insurance_price',
            field=models.FloatField(null=True, verbose_name='Страховка'),
        ),
        migrations.AddField(
            model_name='appeals',
            name='logistic_price',
            field=models.FloatField(null=True, verbose_name='Логистика'),
        ),
        migrations.AddField(
            model_name='appeals',
            name='packaging_price',
            field=models.FloatField(null=True, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='appeals',
            name='prr_price',
            field=models.FloatField(null=True, verbose_name='ПРР'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание товара'),
        ),
    ]
