# Generated by Django 3.2.20 on 2023-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_appeals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='tag',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тег заявки'),
        ),
    ]
