# Generated by Django 3.2.20 on 2023-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_appeals_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='insurance_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страховка'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='logistic_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Логистика'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='packaging_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='prr_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ПРР'),
        ),
    ]
