# Generated by Django 3.2.20 on 2023-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230922_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price_delivery_rf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость доставки в РФ'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_delivery_rf_real',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость доставки в РФ реальная'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
