# Generated by Django 3.2.20 on 2023-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230922_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price_delivery_real',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость доставки реальная'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_delivery_rf_real',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость доставки в РФ реальная'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_purchase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена на сайте'),
        ),
    ]
