# Generated by Django 3.2.20 on 2023-10-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230922_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Супер Администратор', 'Супер Администратор'), ('Администратор', 'Администратор'), ('Логист', 'Логист'), ('Менеджер', 'Менеджер'), ('Закупщик', 'Закупщик'), ('Клиент', 'Клиент')], default='Менеджер', max_length=50, verbose_name='Роль'),
        ),
    ]
