# Generated by Django 3.2.20 on 2023-10-09 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_monthly_net_profit_plan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='План по чистой прибыли в месяц'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Супер Администратор', 'Супер Администратор'), ('РОП', 'РОП'), ('Администратор', 'Администратор'), ('Логист', 'Логист'), ('Менеджер', 'Менеджер'), ('Закупщик', 'Закупщик'), ('Клиент', 'Клиент')], default='Менеджер', max_length=50, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ManagersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit_to_the_company', models.CharField(blank=True, max_length=128, null=True, verbose_name='Чистая прибыль в компанию')),
                ('raised_funds_to_the_company', models.CharField(blank=True, max_length=128, null=True, verbose_name='Привлеченные средства в компанию')),
                ('number_of_new_clients_attracted', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество привлеченных новых клиентов')),
                ('number_of_applications_to_buyers', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество заявок закупщикам')),
                ('amount_of_issued_CP', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сумма выставленных КП')),
                ('number_of_incoming_quality_applications', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество входящих качественных заявок')),
                ('number_of_completed_transactions_based_on_orders', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество совершенных сделок по заявкам')),
                ('number_of_shipments_sent', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество отправленных грузов')),
                ('number_of_goods_issued', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество выданных грузов')),
                ('weight_of_goods_sent', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вес отправленных грузов')),
                ('volume_of_cargo_sent', models.CharField(blank=True, max_length=128, null=True, verbose_name='Объем отправленных грузов')),
                ('number_of_calls', models.CharField(blank=True, max_length=128, null=True, verbose_name='Количество звонков')),
                ('duration_of_calls', models.CharField(blank=True, max_length=128, null=True, verbose_name='Длительность разговоров')),
                ('report_upload_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки отчета')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
