# Generated by Django 3.2.20 on 2023-10-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20231009_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagersData',
            new_name='ManagersReports',
        ),
        migrations.AlterModelOptions(
            name='managersreports',
            options={'verbose_name': 'Отчетность менеджеров', 'verbose_name_plural': 'Отчетность менеджеров'},
        ),
    ]
