# Generated by Django 3.2.20 on 2023-09-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_carrier', models.CharField(choices=[('Ян', 'Ян'), ('Валька', 'Валька'), ('Мурад', 'Мурад'), ('Гелик', 'Гелик')], max_length=50, verbose_name='Перевозчик')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='files/cargo/%Y/%m/%d/', verbose_name='Файлы перевозчиков')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Файлы грузов',
                'verbose_name_plural': 'Файлы грузов',
            },
        ),
        migrations.CreateModel(
            name='CargoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('name_goods', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование товара')),
                ('number_of_seats', models.CharField(max_length=50, verbose_name='Количество мест')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес, кг')),
                ('volume', models.CharField(max_length=50, verbose_name='Объем')),
                ('transportation_tariff', models.CharField(max_length=50, verbose_name='Тариф перевозки')),
                ('cost_goods', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость товара')),
                ('insurance_cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость страховки')),
                ('packaging_cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость упаковки')),
                ('time_from_china', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки с Китайского склада')),
                ('total_cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Итоговая стоимость перевозки')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(True, 'В пути'), (False, 'Прибыл в РФ')], default=True, verbose_name='Статус')),
                ('cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.cargofiles')),
            ],
            options={
                'verbose_name': 'Артикула',
                'verbose_name_plural': 'Артикула',
            },
        ),
    ]
