# Generated by Django 3.2.20 on 2023-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_cargofiles_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoarticle',
            name='status',
            field=models.CharField(choices=[('В пути', 'В пути'), ('Прибыл в РФ', 'Прибыл в РФ')], default='В пути', max_length=50, verbose_name='Статус'),
        ),
    ]
