# Generated by Django 3.2.20 on 2023-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20231005_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoarticle',
            name='responsible_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отвественный менеджер'),
        ),
    ]
